name: PRD17

on: 
  push:
    branches:
      - master

env:
  PUBLIC_NAME: DeepDungeonDex
  INTERNAL_NAME: DeepDungeonDex
  GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER
  GITHUB_SERVER_URL: $GITHUB_SERVER_URL
  GITHUB_REPOSITORY: $GITHUB_REPOSITORY
  GITHUB_SHA: $GITHUB_SHA
jobs:
  pr:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[PR]') || contains(github.event.head_commit.message, '[TEST]')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Bump version and push tag
        id: version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean string
        id: clean
        uses: frabert/replace-string-action@v2.0
        with:
          pattern: '(\[)|(\][\w\d.\]\(:\/]+\))'
          string: ${{ steps.version.outputs.changelog }}
          replace-with: ''
      - name: Setup git user
        run: scripts/setup.sh ${{ secrets.PAT }}
      - name: Get Dalamud Plugins Repo
        run: scripts/dalamudRepo.sh ${{ secrets.PAT }} ${{ github.repository_owner }} ${{ env.PUBLIC_NAME }}
      - name: Create Toml
        run: scripts/setupToml.sh
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
          CHANGELOG: ${{ steps.version.clean.replaced }}
          VERSION: ${{ steps.version.outputs.new_version }}
      - name: Commit, push, and PR
        run: scripts/gitPushPr.sh 
        env: 
          VERSION: ${{ steps.version.outputs.new_version }}
          MESSAGE: "${{ github.event.head_commit.message }}"
          CHANGELOG: "${{ steps.clean.clean.replaced }}"